name: Deploy ImageEditor API to VPS

on:
   push:
      branches:
         - main

jobs:
   deploy:
      runs-on: ubuntu-latest

      steps:
         - name: Deploy to VPS
           uses: appleboy/ssh-action@master
           with:
              host: ${{ secrets.VPS_HOST }}
              username: ${{ secrets.VPS_USERNAME }}
              key: ${{ secrets.VPS_SSH_KEY }}
              script: |
                 echo "🚀 Iniciando deploy da API ImageEditor..."
                 cd ~/meu-servidor

                 echo " PASSO 1/3: Puxando código mais recente..."
                 # Caminho da pasta corrigido para 'imageEditor'
                 git -C ~/imageEditor pull

                 echo " PASSO 2/3: Forçando a reconstrução da imagem sem cache..."
                 # Nome do serviço corrigido para 'rembg-api'
                 docker compose build --no-cache rembg-api

                 echo " PASSO 3/3: Reiniciando o serviço com a nova imagem..."
                 # Nome do serviço corrigido para 'rembg-api'
                 docker compose up -d rembg-api

                 echo "✅ Deploy da API ImageEditor finalizado."
